# Base R Shiny image
FROM rocker/shiny

# Make a directory in the container
RUN mkdir /home/shiny-app

# Install R dependencies
RUN apt-get update && apt-get install -y \
  build-essential \
  libglpk40 \
  libcurl4-openssl-dev \
    libxml2-dev \
    libssl-dev \
    curl
  
RUN R -e "install.packages(c('tidyverse', 'Rcrawler', 'visNetwork','shiny','shinydashboard','shinycssloaders','fresh','DT','shinyBS','faq','igraph','devtools'))"
RUN R -e 'devtools::install_github("salimk/Rcrawler")'

# Copy the Shiny app code
COPY app.R /home/shiny-app/app.R
COPY Rcrawler_modified.R /home/shiny-app/Rcrawler_modified.R
COPY www /home/shiny-app/www

# Expose the application port
EXPOSE 3838


# Run the R Shiny app
#CMD Rscript /home/shiny-app/app.R
CMD ["R", "-e", "shiny::runApp('/home/shiny-app/app.R',port = 3838,host = '0.0.0.0')"]

